apiVersion: apps/v1
kind: Deployment

metadata:
  name: cicd-argocd

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cicd-argocd

  template:
    metadata:
      labels:
        app: cicd-argocd

    spec:
      containers:
        - name: cicd-argocd
          image: pedropedrada/cicd-argocd:cc787e3a1d0b3f8862f5397860781ad57a356df0
          imagePullPolicy: Always

          ports:
            - containerPort: 80