apiVersion: apps/v1
kind: Deployment

metadata:
  name: cicd-argocd

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cicd-argocd

  template:
    metadata:
      labels:
        app: cicd-argocd

    spec:
      containers:
        - name: cicd-argocd
          image: pedropedrada/cicd-argocd:14869247cec0998b2046a580e90860a4c1e10c74
          imagePullPolicy: Always

          ports:
            - containerPort: 80